services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=fincontrol;Username=postgres;Password=postgres
      - Jwt__Key=SuperSecretKey2024SuperSecretKey2024!
      - Jwt__Issuer=FinControl.Api
      - Jwt__Audience=FinControl.Client

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: fincontrol
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: